spring:
  application:
    name: auth-service
  datasource:
    defaultSource: 0
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: dbcp1
  redis:
    database: 0
    host: localhost
    port: 6379

ribbon:
  ReadTimeout: 10000

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 10000
management:
  health:
    db:
      enabled: false

mybatis:
  mapper-locations: classpath:/mybatis/mapping/*Mapper.xml
  config-location: classpath:/mybatis-config.xml
  type-aliases-package: com.uaa.auth.entity

feign:
  httpclient:
    connection-timeout: 60000

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8080/eureka/
