server:
  port: 8080
#spring.mvc.static-path-pattern=/** # Path pattern used for static resources.
spring:
    mvc:
      static-path-pattern: /**
    datasource:
        name: dbtest
        url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: root
        password: 123456
        # druid
#        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
#        filters: stat
#        maxActive: 20
#        initialSize: 1
#        maxWait: 60000
#        minIdle: 1
#        timeBetweenEvictionRunsMillis: 60000
#        minEvictableIdleTimeMillis: 300000
#        validationQuery: select 'x'
#        testWhileIdle: true
#        testOnBorrow: false
#        testOnReturn: false
#        poolPreparedStatements: true
#        maxOpenPreparedStatements: 20
    thymeleaf:
      cache: false #暂时关闭

mybatis:
#  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.wyf.bean

#pagehelper
#pagehelper:
#    helperDialect: mysql
#    reasonable: true
#    supportMethodsArguments: true
#    params: count=countSql